version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    depends_on:
      - app
    container_name: exchange_rates_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    container_name: exchange_rates_app
    depends_on:
      - db
  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
        - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command:
      - "postgres"
      - "-c"
      - 'port=${DB_PORT}'
    container_name: exchange_rates_db
